server:
 port: 8180

spring:
 application:
    name: customer-service
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: shubh123456
    url: jdbc:mariadb://localhost:3306/employee
    username: root
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: create